--------------------------------------------------------
--  File created - Tuesday-December-20-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table XXHTZ_PO_EMEA_FBDI_LINE_LOCATION_STG_TBL
--------------------------------------------------------

  CREATE TABLE "HTZ_CUSTOM"."XXHTZ_PO_EMEA_FBDI_LINE_LOCATION_STG_TBL" 
   (	"FILE_ID" NUMBER, 
	"FLOW_ID" NUMBER, 
	"INTERFACE_LINE_ID" NUMBER, 
	"INTERFACE_LINE_LOCATION_ID" NUMBER, 
	"SCHEDULE_NUM" NUMBER, 
	"SHIP_TO_LOCATION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"SHIP_TO_ORGANIZATION" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"AMOUNT" NUMBER, 
	"QUANTITY" NUMBER, 
	"NEED_BY_DATE" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"PROMISED_DATE" DATE, 
	"SECONDARY_QUANTITY" NUMBER, 
	"SECONDARY_UOM" VARCHAR2(100 BYTE) COLLATE "USING_NLS_COMP", 
	"DESTINATION_TYPE_CODE" VARCHAR2(240 BYTE) COLLATE "USING_NLS_COMP", 
	"REQUESTED_DELIVERY_DATE" DATE, 
	"STATUS" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP", 
	"CREATION_DATE" DATE, 
	"LAST_UPDATE_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"LAST_UPDATED_BY" NUMBER, 
	"LAST_UPDATE_LOGIN" NUMBER, 
	"LOAD_REQUEST_ID" NUMBER, 
	"OBJECT_VERSION_NUMBER" NUMBER
   ) ; 